import type { Metadata } from "next";
import { Inter, Roboto_Condensed, Barlow_Condensed } from "next/font/google";
import { Poppins } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const inter = Inter({ subsets: ["greek"] });
const roboto = Barlow_Condensed({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const warsaw = localFont({
  src: [
    {
      path: "../public/fonts/WarsawGothicSuExt.otf",
    },
  ],
  variable: "--font-warsaw",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={warsaw.variable}>{children}</body>
    </html>
  );
}
